"""
Tests for `sem.scripts.make_validation_table`: turns a validation
`results.csv` (columns `system,pore_type,all_atom_nA,param_nA,
predicted_dev_pct,commit,env,date`) into LaTeX table rows
(`system & pore & all_atom & param & dev \\`), with currents rounded to 2
decimals and the deviation recomputed from full precision
(`100*(param/all_atom-1)`, 2 decimals, explicit sign).

Numpy/csv only -- no pandas, no dolfinx.
"""

import csv

import sem.scripts.make_validation_table as mvt

HEADER = ["system", "pore_type", "all_atom_nA", "param_nA", "predicted_dev_pct", "commit", "env", "date"]

ROWS = [
    # The worked example from the task brief: 41.279 / 40.916 -> -0.88.
    ["15 nm cylinder", "cylindrical", "41.279", "40.916", "-0.85", "1a4ff7f", "sem-env", "2026-09-09"],
    # A positive deviation, to exercise the explicit '+' sign.
    ["30 nm cylinder", "cylindrical", "100.000", "100.280", "0.30", "1a4ff7f", "sem-env", "2026-09-09"],
    ["15 nm double cone", "double_cone", "50.000", "49.500", "-1.00", "1a4ff7f", "sem-env", "2026-09-09"],
]


def _write_csv(path, header=HEADER, rows=ROWS):
    with open(path, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(header)
        writer.writerows(rows)
    return path


def test_compute_deviation_pct_matches_worked_example():
    dev = mvt.compute_deviation_pct(41.279, 40.916)
    assert round(dev, 2) == -0.88


def test_format_row_worked_example():
    row = mvt.format_row("15 nm cylinder", "cylindrical", 41.279, 40.916)
    assert "41.28 & 40.92 & -0.88" in row


def test_format_row_positive_deviation_has_explicit_sign():
    row = mvt.format_row("30 nm cylinder", "cylindrical", 100.000, 100.280)
    assert "100.00 & 100.28 & +0.28" in row


def test_format_row_shape():
    row = mvt.format_row("15 nm cylinder", "cylindrical", 41.279, 40.916)
    fields = [f.strip() for f in row.rstrip().rstrip("\\").rstrip().split("&")]
    assert fields[0] == "15 nm cylinder"
    assert fields[1] == "cylindrical"
    assert fields[2:] == ["41.28", "40.92", "-0.88"]


def test_build_table_header_comment_line(tmp_path):
    csv_path = _write_csv(tmp_path / "results.csv")
    lines = mvt.build_table(str(csv_path))
    assert lines[0].startswith("% generated by make_validation_table.py from ")
    assert str(csv_path) in lines[0]
    assert " on " in lines[0]


def test_build_table_has_one_row_per_csv_row(tmp_path):
    csv_path = _write_csv(tmp_path / "results.csv")
    lines = mvt.build_table(str(csv_path))
    assert len(lines) == 1 + len(ROWS)
    assert "41.28 & 40.92 & -0.88" in lines[1]
    assert "100.00 & 100.28 & +0.28" in lines[2]
    assert "50.00 & 49.50 & -1.00" in lines[3]


def test_build_table_empty_header_only_csv(tmp_path):
    csv_path = _write_csv(tmp_path / "empty.csv", rows=[])
    lines = mvt.build_table(str(csv_path))
    assert len(lines) == 1
    assert lines[0].startswith("%")


def test_build_table_header_date_comes_from_csv_first_row(tmp_path):
    # Regression: the header comment used to always stamp date.today(),
    # making the generated .tex non-deterministic across reruns even
    # though results.csv already records the run date. It should now
    # prefer the CSV's own `date` column (all ROWS share "2026-09-09").
    csv_path = _write_csv(tmp_path / "results.csv")
    lines = mvt.build_table(str(csv_path))
    assert lines[0].endswith(" on 2026-09-09")


def test_build_table_date_override_wins_over_csv(tmp_path):
    csv_path = _write_csv(tmp_path / "results.csv")
    lines = mvt.build_table(str(csv_path), date_str="2030-01-01")
    assert lines[0].endswith(" on 2030-01-01")


def test_main_date_flag_overrides_csv_date(tmp_path):
    csv_path = _write_csv(tmp_path / "results.csv")
    out_path = tmp_path / "rows.tex"

    rc = mvt.main([str(csv_path), "--output", str(out_path), "--date", "2030-01-01"])
    assert rc == 0
    text = out_path.read_text()
    assert text.startswith("% generated by make_validation_table.py")
    assert "on 2030-01-01" in text.splitlines()[0]


def test_main_writes_output_file(tmp_path):
    csv_path = _write_csv(tmp_path / "results.csv")
    out_path = tmp_path / "rows.tex"

    rc = mvt.main([str(csv_path), "--output", str(out_path)])
    assert rc == 0
    assert out_path.is_file()

    text = out_path.read_text()
    assert "41.28 & 40.92 & -0.88" in text
    assert text.startswith("% generated by make_validation_table.py")


def test_main_help_exits_cleanly():
    import pytest

    with pytest.raises(SystemExit) as excinfo:
        mvt.main(["--help"])
    assert excinfo.value.code == 0
