#!/usr/bin/env python3
"""
Turn a validation `results.csv` into LaTeX table rows.

The all-atom-match validation table (`validation/all_atom_match/`) compares
the parametric-fit open-pore current against the true all-atom current for
each of the paper's six systems. Earlier this table was transcribed by
hand into the manuscript, which truncated values; this script generates
the row text directly from `results.csv` so the manuscript can `\\input{}`
it instead.

Expected CSV columns: `system,pore_type,all_atom_nA,param_nA,
predicted_dev_pct,commit,env,date`. Only `system`, `pore_type`,
`all_atom_nA` and `param_nA` are used -- the deviation column in the
output is always recomputed from the full-precision currents (rather than
read from `predicted_dev_pct`, which is `derive_geometry`'s own 1-D
resistance-integral estimate, not the actual FEM comparison this table
reports).

Numpy/csv only (no pandas), matching the rest of the dolfinx-free tooling
in `sem/scripts/`.

CLI: `python -m sem.scripts.make_validation_table results.csv --output rows.tex`.
"""

import argparse
import csv
import sys
from datetime import date

import numpy as np


def compute_deviation_pct(all_atom_nA, param_nA):
    """`100 * (param_nA / all_atom_nA - 1)`, at full precision."""
    return float(100.0 * (float(param_nA) / float(all_atom_nA) - 1.0))


def format_row(system, pore_type, all_atom_nA, param_nA):
    """
    One LaTeX table row: `system & pore & all_atom & param & dev \\`, with
    currents rounded to 2 decimals and the deviation (recomputed from the
    full-precision currents) rounded to 2 decimals with an explicit sign.
    """
    dev_pct = compute_deviation_pct(all_atom_nA, param_nA)
    all_atom_rounded = float(np.round(float(all_atom_nA), 2))
    param_rounded = float(np.round(float(param_nA), 2))
    dev_rounded = float(np.round(dev_pct, 2))
    return (
        f"{system} & {pore_type} & {all_atom_rounded:.2f} & "
        f"{param_rounded:.2f} & {dev_rounded:+.2f} \\\\"
    )


def read_rows(csv_path):
    with open(csv_path, newline="") as fh:
        reader = csv.DictReader(fh)
        return list(reader)


def build_table(csv_path):
    """Return the full list of output lines: a header comment line
    followed by one LaTeX row per CSV data row (possibly none)."""
    rows = read_rows(csv_path)
    lines = [
        f"% generated by make_validation_table.py from {csv_path} on {date.today().isoformat()}"
    ]
    for row in rows:
        lines.append(
            format_row(
                row["system"],
                row["pore_type"],
                row["all_atom_nA"],
                row["param_nA"],
            )
        )
    return lines


def _build_arg_parser():
    parser = argparse.ArgumentParser(
        prog="make_validation_table",
        description="Generate LaTeX table rows from an all-atom-match validation results.csv.",
    )
    parser.add_argument("csv_path", metavar="CSV", help="Path to the validation results.csv")
    parser.add_argument("--output", required=True, help="Output .tex file to write the rows to")
    return parser


def main(argv=None):
    """CLI entry point. Returns a process exit code (0 on success)."""
    parser = _build_arg_parser()
    args = parser.parse_args(argv)

    lines = build_table(args.csv_path)
    with open(args.output, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"Wrote {len(lines) - 1} row(s) to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
