#!/usr/bin/env python3
"""
Downsample an existing .bin conductivity/distance grid onto coarser resolutions.

Example:
    python -m sem.scripts.resample_bin \
        --input vertical_movement_cylindrical_pore.bin \
        --resolutions 1.5 2.0 2.5 3.0 4.0 5.0 \
        --output-dir grid_conv
"""

import argparse
from pathlib import Path

import numpy as np
from scipy.interpolate import RegularGridInterpolator

try:
    from ..utils import readbinGrid
except ImportError:  # pragma: no cover - relative import fallback
    from sem.utils import readbinGrid

try:
    from .gen_dist import write_binary_file
except ImportError:  # pragma: no cover - relative import fallback
    from sem.scripts.gen_dist import write_binary_file


def _parse_args():
    parser = argparse.ArgumentParser(
        description="Resample an existing binary grid to specified resolutions."
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Source .bin file generated by gen_dist or SEM.",
    )
    parser.add_argument(
        "--resolutions",
        nargs="+",
        type=float,
        required=True,
        help="Target grid spacings (Å).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory to place resampled .bin files (defaults to input directory).",
    )
    parser.add_argument(
        "--prefix",
        type=str,
        default=None,
        help="Custom filename prefix (defaults to input stem).",
    )
    return parser.parse_args()


def _build_interpolator(grid, origin, spacing):
    nx, ny, nz = grid.shape
    x = origin[0] + np.arange(nx, dtype=np.float64) * spacing[0]
    y = origin[1] + np.arange(ny, dtype=np.float64) * spacing[1]
    z = origin[2] + np.arange(nz, dtype=np.float64) * spacing[2]
    return RegularGridInterpolator(
        (x, y, z),
        grid,
        bounds_error=False,
        fill_value=None,
    ), (x[0], x[-1]), (y[0], y[-1]), (z[0], z[-1])


def _generate_axis(origin_val, end_val, target_spacing):
    length = end_val - origin_val
    n_points = int(np.floor(length / target_spacing)) + 1
    # Ensure we include the final endpoint if within tolerance
    coords = origin_val + np.arange(n_points, dtype=np.float64) * target_spacing
    if coords[-1] < end_val - 1e-8:
        coords = np.append(coords, end_val)
    return coords


def _resample_grid(interpolator, axis_bounds, target_spacing):
    (x0, x1), (y0, y1), (z0, z1) = axis_bounds
    x_new = _generate_axis(x0, x1, target_spacing)
    y_new = _generate_axis(y0, y1, target_spacing)
    z_new = _generate_axis(z0, z1, target_spacing)

    X, Y, Z = np.meshgrid(x_new, y_new, z_new, indexing="ij")
    sample_points = np.column_stack([X.ravel(), Y.ravel(), Z.ravel()])
    sampled = interpolator(sample_points).reshape(X.shape)
    return sampled.astype(np.float32), (len(x_new), len(y_new), len(z_new))


def resample_bin_file(input_path, resolutions, output_dir=None, prefix=None):
    grid, _, _, metadata = readbinGrid(str(input_path), return_metadata=True)
    origin = metadata["origin"].astype(np.float64)
    spacing = metadata["spacing"].astype(np.float64)

    interpolator, x_bounds, y_bounds, z_bounds = _build_interpolator(grid, origin, spacing)
    axis_bounds = (x_bounds, y_bounds, z_bounds)

    output_dir = output_dir or input_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    base_prefix = prefix or input_path.stem

    for target_spacing in resolutions:
        if target_spacing <= 0:
            raise ValueError(f"Resolution must be positive, got {target_spacing}")
        coarse_grid, shape = _resample_grid(interpolator, axis_bounds, target_spacing)

        # write_binary_file expects array shaped (nz, ny, nx)
        output_array = np.transpose(coarse_grid, (2, 1, 0))
        filename = output_dir / f"{base_prefix}_{target_spacing:.2f}A.bin"
        write_binary_file(output_array, origin.tolist(), target_spacing, str(filename))

        print(
            f"Wrote {filename} | shape {shape} | spacing {target_spacing:.2f} Å"
        )


def main():
    args = _parse_args()
    resample_bin_file(
        input_path=args.input,
        resolutions=args.resolutions,
        output_dir=args.output_dir,
        prefix=args.prefix,
    )


if __name__ == "__main__":
    main()
